resolver: lts-8.5
allow-newer: true
packages:
- '.'
- '../lnforum-api'
- '../lnforum-sanitize'
- '../lnforum-validate'
- '../lnforum-types-gen'
- '../haskell-api-helpers'
- '../haskell-api-helpers-shared'
- '../haskell-ebyam'
- '../haskell-rehtie'
- '../haskell-ifte'
- '../haskell-either-helpers'
extra-deps:
- html-entities-1.1.4.2
- web-routes-0.27.14.2
flags: {}
extra-package-dbs: []
